version: '3'
services:
  app:
    image: godric/towerfall-scores
    build: .
    ports:
    - "3000:3000"
    volumes:
    - ./logs:/logs
    environment:
    - PORT=3000
    - LOGFILE=/logs/redux.log
    - PASSWORD=

